"""Document Generator Agent - Generates structured planning documents."""

import os
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from crewai import Agent, Task

from src.agents.base import BaseAgent
from src.memory.base import Discussion


@dataclass
class PlanningDocument:
    """Generated planning document."""

    discussion_id: str
    project_id: str
    title: str
    version: str
    content: str
    file_path: str
    generated_at: datetime = field(default_factory=datetime.now)


class DocumentGenerator(BaseAgent):
    """Document Generator agent for creating structured planning documents.

    The Document Generator focuses on:
    - Extracting design decisions from discussions
    - Creating well-structured planning documents
    - Following consistent document templates
    - Version management of generated documents
    """

    role_name = "document_generator"

    def __init__(self, llm: Any | None = None, data_dir: str = "data/projects") -> None:
        """Initialize the Document Generator agent.

        Args:
            llm: Optional LLM instance to use.
            data_dir: Base directory for storing documents.
        """
        self._llm = llm
        self._data_dir = data_dir
        self._agent: Agent | None = None
        # Fixed configuration for document generator
        self._config = {
            "role": "Planning Document Generator",
            "goal": "Create well-structured, comprehensive planning documents from discussion content",
            "backstory": """You are an expert technical writer who specializes in game design
            documentation. You excel at organizing complex design discussions into clear,
            actionable planning documents. Your documents help development teams understand
            the design vision and implementation requirements.""",
            "focus_areas": [
                "Document structure and organization",
                "Clear technical specifications",
                "Design rationale documentation",
                "Action items and milestones",
            ],
        }

    @property
    def config(self) -> dict[str, Any]:
        """Get the role configuration dictionary."""
        return self._config

    @property
    def role(self) -> str:
        """Get the agent's role title."""
        return self._config.get("role", "")

    @property
    def goal(self) -> str:
        """Get the agent's primary goal."""
        return self._config.get("goal", "")

    @property
    def backstory(self) -> str:
        """Get the agent's backstory/personality."""
        return self._config.get("backstory", "")

    @property
    def focus_areas(self) -> list[str]:
        """Get the agent's focus areas/expertise."""
        return self._config.get("focus_areas", [])

    def get_tools(self) -> list[Any]:
        """Get tools available to the Document Generator.

        Returns:
            Empty list (no tools needed for document generation).
        """
        return []

    def build_agent(self) -> Agent:
        """Build and return the CrewAI Agent instance.

        Returns:
            Configured CrewAI Agent instance.
        """
        if self._agent is None:
            agent_kwargs: dict[str, Any] = {
                "role": self.role,
                "goal": self.goal,
                "backstory": self.backstory,
                "tools": self.get_tools(),
                "verbose": False,
                "allow_delegation": False,
            }

            if self._llm is not None:
                agent_kwargs["llm"] = self._llm

            self._agent = Agent(**agent_kwargs)

        return self._agent

    def _get_document_template(self, project_name: str, discussion_id: str) -> str:
        """Get the document template.

        Args:
            project_name: The project name.
            discussion_id: The discussion ID.

        Returns:
            Markdown template string.
        """
        return f"""# {{project_name}} - Planning Document

> Generated: {{timestamp}}
> Source Discussion: {discussion_id}
> Version: {{version}}

## Overview

{{brief_overview}}

## Core Design

### Design Point 1
{{design_point_1}}

### Design Point 2
{{design_point_2}}

## Decisions and Rationale

| Topic | Perspectives | Final Decision |
|-------|--------------|----------------|
{{decisions_table}}

## Open Items

{{open_items}}

---
*This document was generated by the AI Planning Team*
"""

    def create_document_task(self, discussion: Discussion, project_name: str = "") -> Task:
        """Create a task for generating a planning document.

        Args:
            discussion: The discussion to generate document from.
            project_name: Optional project name override.

        Returns:
            CrewAI Task for generating the document.
        """
        # Format messages for context
        messages_text = "\n\n".join(
            f"**{msg.agent_role}**: {msg.content}" for msg in discussion.messages
        )

        effective_project_name = project_name or discussion.project_id

        description = f"""
Please analyze the following discussion and generate a structured planning document.

**Project Name**: {effective_project_name}
**Discussion Topic**: {discussion.topic}
**Discussion ID**: {discussion.id}

**Discussion Content**:
{messages_text}

Generate a comprehensive planning document in Markdown format with the following structure:

1. **Overview**: A brief (1-2 paragraph) description of the core design being discussed

2. **Core Design**: Organized sections for each major design point discussed.
   Extract the key design decisions and their details.

3. **Decisions and Rationale**: A table summarizing:
   - The topic/issue discussed
   - Different perspectives from participants
   - The final decision or consensus (if reached)

4. **Open Items**: A checklist of unresolved questions or items needing further work

Format the document professionally and ensure it captures all important design details.
Use proper Markdown formatting including headers, bullet points, and tables.
"""

        expected_output = """A complete planning document in Markdown format containing:
- Title and metadata header
- Overview section
- Core Design sections
- Decisions table
- Open items checklist"""

        return Task(
            name=f"generate-doc-{discussion.id}",
            description=description,
            expected_output=expected_output,
            agent=self.build_agent(),
        )

    def _generate_version(self, discussion_id: str) -> str:
        """Generate a version string for the document.

        Args:
            discussion_id: The discussion ID.

        Returns:
            Version string in format {discussion_id}-{yyyyMMdd-HHmm}.
        """
        timestamp = datetime.now().strftime("%Y%m%d-%H%M")
        return f"{discussion_id}-{timestamp}"

    def _ensure_metadata_header(
        self,
        content: str,
        discussion: Discussion,
        project_name: str,
        version: str,
    ) -> str:
        """Ensure the document contains a metadata header with source discussion info."""
        lines = content.splitlines()
        for line in lines[:10]:
            if line.lower().startswith("> source discussion:"):
                return content

        effective_name = project_name or discussion.project_id
        metadata_block = [
            f"> Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"> Source Discussion: {discussion.id}",
            f"> Version: {version}",
            "",
        ]

        if content.lstrip().startswith("#") and lines:
            header = lines[0]
            rest = lines[1:]
            return "\n".join([header, "", *metadata_block, *rest]).strip() + "\n"

        header = [
            f"# {effective_name} - Planning Document",
            "",
            *metadata_block,
        ]
        return "\n".join(header) + "\n" + content

    def _get_drafts_dir(self, project_id: str) -> Path:
        """Get the drafts directory for a project.

        Args:
            project_id: The project ID.

        Returns:
            Path to the drafts directory.
        """
        return Path(self._data_dir) / project_id / "drafts"

    def save_document(
        self,
        content: str,
        discussion: Discussion,
        project_name: str = "",
    ) -> PlanningDocument:
        """Save a generated document to disk.

        Args:
            content: The document content.
            discussion: The source discussion.
            project_name: Optional project name.

        Returns:
            PlanningDocument with file path.
        """
        version = self._generate_version(discussion.id)
        drafts_dir = self._get_drafts_dir(discussion.project_id)

        # Ensure directory exists
        os.makedirs(drafts_dir, exist_ok=True)

        # Generate filename
        filename = f"{version}.md"
        file_path = drafts_dir / filename

        content = self._ensure_metadata_header(content, discussion, project_name, version)

        # Write file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

        return PlanningDocument(
            discussion_id=discussion.id,
            project_id=discussion.project_id,
            title=f"{project_name or discussion.project_id} - Planning Document",
            version=version,
            content=content,
            file_path=str(file_path),
            generated_at=datetime.now(),
        )

    def list_versions(self, project_id: str, discussion_id: str | None = None) -> list[dict]:
        """List all document versions for a project.

        Args:
            project_id: The project ID.
            discussion_id: Optional discussion ID filter.

        Returns:
            List of version info dicts.
        """
        drafts_dir = self._get_drafts_dir(project_id)

        if not drafts_dir.exists():
            return []

        versions = []
        for file_path in drafts_dir.glob("*.md"):
            # Parse version from filename
            version = file_path.stem

            # Filter by discussion_id if provided
            if discussion_id:
                short_id = discussion_id[:8] if len(discussion_id) > 8 else discussion_id
                if not (version.startswith(discussion_id) or version.startswith(short_id)):
                    continue

            versions.append({
                "version": version,
                "file_path": str(file_path),
                "project_id": project_id,
                "created_at": datetime.fromtimestamp(file_path.stat().st_mtime).isoformat(),
            })

        # Sort by creation time, newest first
        versions.sort(key=lambda x: x["created_at"], reverse=True)
        return versions

    def load_document(self, file_path: str) -> str | None:
        """Load a document from disk.

        Args:
            file_path: Path to the document file.

        Returns:
            Document content or None if not found.
        """
        path = Path(file_path)
        if not path.exists():
            return None

        with open(path, encoding="utf-8") as f:
            return f.read()

    def __repr__(self) -> str:
        """Return string representation of the agent."""
        return f"<DocumentGenerator(role='{self.role}')>"
