"""Checkpoint data models for discussion milestone tracking."""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class CheckpointType(str, Enum):
    """Checkpoint type determines behavior and UI rendering."""

    SILENT = "silent"
    PROGRESS = "progress"
    DECISION = "decision"


class DecisionOption(BaseModel):
    """A single option in a DECISION checkpoint."""

    id: str  # 选项 ID (A/B/C/D)
    label: str  # 选项标题
    description: str  # 选项说明


class Checkpoint(BaseModel):
    """Checkpoint data model.

    Generated by lead planner at the end of each discussion round.
    Three types: SILENT (no output), PROGRESS (non-blocking notice),
    DECISION (blocking, requires producer response).
    """

    id: str  # checkpoint ID (e.g., "cp_001")
    discussion_id: str
    type: CheckpointType
    round_num: int  # 产出此 checkpoint 的轮次
    section_id: str | None = None  # 关联的章节 ID

    # PROGRESS fields
    title: str = ""  # 进展标题
    summary: str = ""  # 进展摘要
    key_points: list[str] = Field(default_factory=list)

    # DECISION fields
    question: str = ""  # 需要回答的问题
    context: str = ""  # 决策背景
    options: list[DecisionOption] = Field(default_factory=list)  # 2-4 个选项
    allow_free_input: bool = True  # 是否允许自由输入

    # Decision response
    response: str | None = None  # 用户选择的选项 ID 或自由输入
    response_text: str | None = None  # 用户的补充说明
    responded_at: str | None = None

    # Metadata
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    announced: bool = False  # 决策是否已被主策划公开宣布


class PendingProducerMessage(BaseModel):
    """Producer message pending processing by lead planner."""

    content: str
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class PendingProducerMessages(BaseModel):
    """Queue of pending producer messages in a discussion."""

    messages: list[PendingProducerMessage] = Field(default_factory=list)
    pending: bool = False
